bag_of_holding/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    path('', include('user.urls')),
    path("__reload__/", include("django_browser_reload.urls")),

    re_path(r'^rosetta/', include('rosetta.urls'))
]

inventory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="inventory_index")
]

user/urls.py
from django.urls import path

from . import views
from .views import user_login

urlpatterns = [
    path("", views.UserIndexView.as_view(), name="index"),
    path("login/", user_login, name="login"),
]

inventory/models.py
from typing import Optional

from django.db import models
from django.contrib.auth.models import User
from .constants import RARITY_CHOICES, WEAPON_TYPE_CHOICES, ARMOR_TYPE_CHOICES, RECHARGE_TYPES
from django.utils.translation import gettext_lazy as _


class ItemPrice(models.Model):
    pp = models.FloatField(null=True, blank=True)
    ep = models.FloatField(null=True, blank=True)
    gp = models.FloatField(null=True, blank=True)
    sp = models.FloatField(null=True, blank=True)
    cp = models.FloatField(null=True, blank=True)

    def __str__(self):
        return f'gp: {self.gp} - sp: {self.sp} - cp: {self.cp}'


class BaseItem(models.Model):
    name = models.CharField(max_length=200)
    creation_date = models.DateTimeField(_("Date created"))
    acquisition_date = models.CharField(_("Date acquired"), max_length=200, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    price = models.OneToOneField(ItemPrice, on_delete=models.CASCADE, related_name='base_item')
    is_party_owned = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    rarity = models.CharField(choices=RARITY_CHOICES, max_length=200, default='common')
    description = models.TextField(default="", null=True, blank=True)
    attunement_required = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.name}'


class RechargeableItem(models.Model):
    name = models.CharField(max_length=200)
    charges = models.IntegerField(default=0, help_text=_("Remaining charges"), blank=True, null=True)
    max_charges = models.IntegerField(default=0, help_text=_("Maximum charges"), blank=True, null=True)
    recharge_type = models.CharField(choices=RECHARGE_TYPES, max_length=200)

    class Meta:
        abstract = True

    def use_charge(self) -> bool:
        if self.charges is not None and self.charges > 0:
            self.charges -= 1
            self.save()
            return True
        return False

    def recharge(self) -> None:
        if self.max_charges is not None:
            self.charges = self.max_charges
            self.save()

    def __str__(self) -> str:
        return f'{self.name} ({_("Rechargeable Item")})'


class Weapon(BaseItem):
    weapon_type = models.CharField(choices=WEAPON_TYPE_CHOICES, max_length=50)
    damage = models.CharField(max_length=50)
    properties = models.TextField()

    def __str__(self) -> str:
        return f'{self.name} ({_("Weapon")})'


class Armor(BaseItem):
    armor_type = models.CharField(choices=ARMOR_TYPE_CHOICES, max_length=50)
    armor_class = models.CharField(max_length=50)
    strength_requirement = models.IntegerField(null=True, blank=True)
    stealth_disadvantage = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.name} ({_("Armor")})'


class Potion(BaseItem):
    effect = models.TextField()
    duration = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self) -> str:
        return f'{self.name} ({_("Potion")})'


class Scroll(BaseItem):
    spell_name = models.CharField(max_length=200)
    spell_level = models.IntegerField()
    spell_effects = models.TextField()

    def __str__(self) -> str:
        return f'{self.name} ({_("Scroll")})'


class WondrousItem(BaseItem, RechargeableItem):
    effect = models.TextField()

    def __str__(self) -> str:
        return f'{self.name} ({_("Wondrous Item")})'


class Wand(BaseItem, RechargeableItem):
    effect = models.TextField()

    def __str__(self) -> str:
        return f'{self.name} ({_("Wand")})'


class Staff(BaseItem, RechargeableItem):
    effect = models.TextField()

    def __str__(self) -> str:
        return f'{self.name} ({_("Staff")})'


class Rod(BaseItem, RechargeableItem):
    effect = models.TextField()

    def __str__(self) -> str:
        return f'{self.name} ({_("Rod")})'

user/models.py
from django.db import models

inventory/views.py
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views import generic

from .models import BaseItem


class IndexView(generic.ListView):
    template_name = "inventory/index.html"
    paginate_by = 20
    model = BaseItem
    ordering = ['name']

    def get_queryset(self):
        queryset = super().get_queryset()
        search_term = self.request.GET.get('search_term', '')
        if search_term:
            queryset = queryset.filter(Q(name__icontains=search_term) | Q(description__icontains=search_term))
        return queryset

user/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login


class UserIndexView(TemplateView):
    template_name = "user/index.html"


def user_login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/inventory')
        else:
            return render(request, 'user/index.html', {'error_message': 'Invalid login. Please try again.'})
    else:
        return render(request, 'user/index.html')

inventory/templates/inventory/index.html
{% extends '_base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<body class="bg-[var(--main)] leading-normal tracking-normal text-[var(--neutral-da)]">
    {% include 'header.html' %}
    <main class="grid align-center p-8 m-8">
        <div class="py-3 justify-self-end min-w-2xl">
            <div class="flex gap-4 w-full">
                <label class="sr-only">{% trans 'Search' %}</label>
                    <form action="{% url 'inventory_index' %}" method="get" class="flex gap-4 w-96 cursor-pointer">
                      <input type="text" name="search_term" id="hs-table-with-pagination-search"
                           class="py-2 px-3 ps-9 block w-full border-gray-200 shadow-sm rounded-lg text-sm focus:z-10
                           focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none"
                           placeholder="{% trans 'Search for items' %}">
                        <button type="submit" class="transition ease-in-out bg-[var(--secondary)] p-4 w-fit text-[(--neutral-da)]  hover:bg-[var(--neutral-li)] hover:-translate-y-1 duration-300 font-semibold rounded-lg" onclick="searchItem()">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </button>
                    </form>
            </div>
        </div>
        <div class="overflow-auto custom-scrollbar">
            <table class="min-w-full divide-y divide-gray-200 table-fixed">
                <thead class="bg-[var(--secondary)]">
                    <tr>
                        <th scope="col" class="py-3 px-4 pe-0">
                            <div class="flex items-center h-5">
                                <input id="hs-table-pagination-checkbox-all" type="checkbox" class="border-gray-200 rounded
                                text-[var(--secondary)] focus:ring-[var(--secondary)]">
                                <label for="hs-table-pagination-checkbox-all" class="sr-only">Checkbox</label>
                            </div>
                        </th>
                        <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-[var(--neutral-da)] uppercase">{% trans 'Name' %}</th>
                        <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-[var(--neutral-da)] uppercase">{% trans 'Rarity' %}</th>
                        <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-[var(--neutral-da)] uppercase">{% trans 'Price' %}</th>
                        <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-[var(--neutral-da)] uppercase">{% trans 'Description' %}</th>
                        <th scope="col" class="px-6 py-3 text-start text-xs font-medium text-[var(--neutral-da)] uppercase">{% trans 'Acquisition date' %}</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200">
                {% for item in object_list %}
                    {% if item.is_available%}
                        <tr class="hover:bg-gray-100 cursor-pointer" onclick="toggleDetails(this)">
                            <td class="py-3 ps-4">
                                <div class="flex items-center h-5">
                                    <input id="hs-table-pagination-checkbox-1" type="checkbox" class="border-gray-200 rounded
                                    text-[var(--secondary)] focus:ring-[var(--secondary)]" onclick="event.stopPropagation()">
                                    <label for="hs-table-pagination-checkbox-1" class="sr-only">Checkbox</label>
                                </div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">{{ item.name|default:"??" }}</td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800">{{ item.get_rarity_display|default:"-" }}</td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800">
                                <div class="price-holder flex gap-4">
                                     <div class="gp-holder flex gap-2 items-center">
                                         <div class="coin-holder w-[1rem]" >
                                            <img src="{% static 'inventory/img/gp_nobg.svg' %}"  alt="gold coin">
                                         </div>
                                         {{item.price.gp|default:"-"}}
                                     </div>
                                    <div class="gp-holder flex gap-2 items-center">
                                         <div class="coin-holder w-[1rem]" >
                                            <img src="{% static 'inventory/img/sp_nobg.svg' %}"  alt="silver coin">
                                         </div>
                                         {{item.price.sp|default:"-"}}
                                     </div>
                                    <div class="gp-holder flex gap-2 items-center">
                                         <div class="coin-holder w-[1rem]" >
                                            <img src="{% static 'inventory/img/cp_nobg.svg' %}"  alt="copper coin">
                                         </div>
                                         {{item.price.cp|default:"-"}}
                                     </div>
                                </div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800 max-w-[200px] overflow-hidden text-ellipsis" title="{{ item.description|default:'No data' }}">{{ item.description|default:"No data" }}</td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-800">{{ item.acquisition_date|default:"Anaenis" }}</td>
                        </tr>
                        <tr class="details-row hidden">
                            <td colspan="6" class="px-6 py-4">
                                <!-- Additional details can be added here -->
                                <p>Additional details for {{ item.name }}</p>
                            </td>
                        </tr>
                    {% endif %}
                {% empty %}
                    <tr>
                        <td colspan="7" class="text-center text-[var(--neutral-li)] py-4">{% trans 'Ups, looks like your party is broke!' %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% include 'inventory/pagination.html' %}
        </div>
    </main>
    <script src="{% static 'inventory/js/inventory.js' %}"></script>
    <script>
        const CSRF_TOKEN = '{{ csrf_token }}'
    </script>
</body>
{% endblock %}

inventory/templates/inventory/pagination.html
<div class="pagination">
    {% if is_paginated %}
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">last &raquo;</a>
            {% endif %}
        </span>
    {% endif %}
</div>

theme/templates/_base.html
{% load static tailwind_tags %}

{% block css %}
{% endblock %}

<html>
    <head>
        <title>Bag of holding</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
            <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
            <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
            {% tailwind_css %}
    </head>

    {% block content %}

    {% endblock %}
</html>

theme/templates/_base_button.html
<button type="{{type}}" class="transition ease-in-out bg-[var(--secondary)] p-4 w-fit text-[(--neutral-da)]  hover:bg-[var(--neutral-li)] hover:-translate-y-1 duration-300 font-semibold rounded-lg">{{text}}</button>

theme/templates/_base_input.html
<div class="w-full max-w-xs md:max-w-md p-5 font-mono grid justify-self-center">
  <label class="text-[var(--neutral-da)] text-md font-bold mb-2" for="input-{{id}}">{{ label }}</label>
  <input
    class="text-sm custom-input w-full py-2 border border-[var(--pal-orange)] rounded-lg shadow-sm transition duration-300 ease-in-out transform focus:-translate-y-1 focus:outline-[var(--pal-orange)] hover:shadow-lg hover:border-[var(--pal-orange)] bg-text-[var(--neutral-da)]"
    placeholder="{{placeholder}}"
    type="{{type|default:'text'}}"
    id="input-{{id}}"
    name="{{name}}"
  />
</div>

theme/templates/header.html
<header class="bg-[var(--secondary)] h-16 flex px-8 py-4 items-center">
    <div class="text-[var(--neutral-li)] flex gap-4 items-center">
        <i class="fa-solid fa-dice-d20 fa-2xl"></i>
        <h1 class="font-bold text-xl">BAG OF HOLDING</h1>
    </div>
</header>

user/templates/user/index.html
{% extends '_base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'user/user.css' %}">
{% endblock %}


{% block content %}
    <body class="grid md:grid-cols-5 grid-cols-1">
        <section id="img-section" class="hidden md:col-span-4 md:order-last md:block"></section>
        <section id="login-section" class="bg-[var(--main)] grid grid-rows-12">
            <h1 class="bg-[var(--pal-orange)] text-[[var(--pal-orange)] p-8 text-2xl hover:cursor-pointer">BAG OF HOLDING</h1>
            <div class="form grid self-center row-span-10">
                {% include 'user/login_form.html' %}
            </div>
        </section>
    </body>
{% endblock %}

user/templates/user/login_form.html
{% load i18n %}

<form action="{% url 'login' %}" method="post" class="w-full p-4 grid items-center">
    {% csrf_token %}

    {% trans "User" as user_label %}
    {% trans "Password" as password_label %}

    {% include '_base_input.html' with id="input-username" required="true" name="username" label=user_label %}
    {% include '_base_input.html' with id="input-password" required="true" name="password" type="password" label=password_label %}

    {% if error_message%}
        <p class="text-[var(--neutral-da] mx-8"><span class="text-[var(--secondary)]">* </span>{{error_message}}</p>
    {% endif %}
    <div class="btn-holder flex justify-end mx-8 my-4">
        {% trans 'Roll for initiative!' as roll_label %}
        {% include '_base_button.html' with id="btn-login" text=roll_label type='submit' %}
    </div>
</form>